config/routes.rb
Rails.application.routes.draw do
  resources :workouts
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/workout.rb
class Workout < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :set_workout, only: %i[ show edit update destroy ]

  # GET /workouts or /workouts.json
  def index
    @workouts = Workout.all
  end

  # GET /workouts/1 or /workouts/1.json
  def show
  end

  # GET /workouts/new
  def new
    @workout = Workout.new
  end

  # GET /workouts/1/edit
  def edit
  end

  # POST /workouts or /workouts.json
  def create
    @workout = Workout.new(workout_params)

    respond_to do |format|
      if @workout.save
        format.html { redirect_to workout_url(@workout), notice: "Workout was successfully created." }
        format.json { render :show, status: :created, location: @workout }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workouts/1 or /workouts/1.json
  def update
    respond_to do |format|
      if @workout.update(workout_params)
        format.html { redirect_to workout_url(@workout), notice: "Workout was successfully updated." }
        format.json { render :show, status: :ok, location: @workout }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @workout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workouts/1 or /workouts/1.json
  def destroy
    @workout.destroy!

    respond_to do |format|
      format.html { redirect_to workouts_url, notice: "Workout was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_workout
      @workout = Workout.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def workout_params
      params.require(:workout).permit(:name, :duration, :calories_burned, :exercise_type, :log_date, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnapFit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/workouts/_form.html.erb
<%= form_with(model: workout) do |form| %>
  <% if workout.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(workout.errors.count, "error") %> prohibited this workout from being saved:</h2>

      <ul>
        <% workout.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.number_field :duration %>
  </div>

  <div>
    <%= form.label :calories_burned, style: "display: block" %>
    <%= form.number_field :calories_burned %>
  </div>

  <div>
    <%= form.label :exercise_type, style: "display: block" %>
    <%= form.text_area :exercise_type %>
  </div>

  <div>
    <%= form.label :log_date, style: "display: block" %>
    <%= form.date_field :log_date %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/workouts/_workout.html.erb
<div id="<%= dom_id workout %>">
  <p>
    <strong>Name:</strong>
    <%= workout.name %>
  </p>

  <p>
    <strong>Duration:</strong>
    <%= workout.duration %>
  </p>

  <p>
    <strong>Calories burned:</strong>
    <%= workout.calories_burned %>
  </p>

  <p>
    <strong>Exercise type:</strong>
    <%= workout.exercise_type %>
  </p>

  <p>
    <strong>Log date:</strong>
    <%= workout.log_date %>
  </p>

  <p>
    <strong>User:</strong>
    <%= workout.user_id %>
  </p>

</div>

app/views/workouts/edit.html.erb
<h1>Editing workout</h1>

<%= render "form", workout: @workout %>

<br>

<div>
  <%= link_to "Show this workout", @workout %> |
  <%= link_to "Back to workouts", workouts_path %>
</div>

app/views/workouts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Workouts</h1>

<div id="workouts">
  <% @workouts.each do |workout| %>
    <%= render workout %>
    <p>
      <%= link_to "Show this workout", workout %>
    </p>
  <% end %>
</div>

<%= link_to "New workout", new_workout_path %>

app/views/workouts/new.html.erb
<h1>New workout</h1>

<%= render "form", workout: @workout %>

<br>

<div>
  <%= link_to "Back to workouts", workouts_path %>
</div>

app/views/workouts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @workout %>

<div>
  <%= link_to "Edit this workout", edit_workout_path(@workout) %> |
  <%= link_to "Back to workouts", workouts_path %>

  <%= button_to "Destroy this workout", @workout, method: :delete %>
</div>